import { Profile, Workout, Challenge, AppNotification, Achievement } from '@/types/database'
import { EnrichedWorkout, EnrichedChallenge } from '@/types/app'

export const SEED_PROFILES: Profile[] = [
  {
    id: 'usr_me',
    username: 'selcuk',
    display_name: 'Selçuk Yılmaz',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Maraton koşucusu ve fitness tutkunu 🏃‍♂️⚡',
    weekly_goal: 4,
    current_streak: 5,
    longest_streak: 12,
    total_xp: 340,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_ahmet',
    username: 'ahmet_run',
    display_name: 'Ahmet Kaya',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Sabah insanı, 5k sevdalısı 🏃🏻‍♂️',
    weekly_goal: 5,
    current_streak: 7,
    longest_streak: 15,
    total_xp: 520,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_zeynep',
    username: 'zeynep_fit',
    display_name: 'Zeynep Demir',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    bio: 'Crossfit & Yoga 🧘‍♀️💪🏻',
    weekly_goal: 3,
    current_streak: 4,
    longest_streak: 8,
    total_xp: 290,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_mehmet',
    username: 'mehmet_lift',
    display_name: 'Mehmet Öztürk',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    bio: 'Leg day asla atlanmaz! 🏋️‍♂️',
    weekly_goal: 4,
    current_streak: 2,
    longest_streak: 9,
    total_xp: 410,
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_can',
    username: 'can_pedal',
    display_name: 'Can Arslan',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    bio: 'Bisiklet rotaları ve açık hava 🚴‍♂️',
    weekly_goal: 3,
    current_streak: 3,
    longest_streak: 6,
    total_xp: 210,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const SEED_WORKOUTS: EnrichedWorkout[] = [
  {
    id: 'wkt_1',
    user_id: 'usr_ahmet',
    type: 'Running',
    duration_minutes: 34,
    distance_km: 5.4,
    calories: 380,
    notes: 'Akşam sahil koşusu harikaydı! Tempo gayet iyiydi 🔥',
    image_url: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&auto=format&fit=crop&q=80',
    workout_date: new Date().toISOString().split('T')[0],
    visibility: 'friends',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    user: SEED_PROFILES[1],
    reactions: [
      { reaction_type: '🔥', count: 4, has_user_reacted: true, user_ids: ['usr_me', 'usr_zeynep', 'usr_mehmet', 'usr_can'] },
      { reaction_type: '💪', count: 2, has_user_reacted: false, user_ids: ['usr_zeynep', 'usr_can'] },
      { reaction_type: '❤️', count: 3, has_user_reacted: true, user_ids: ['usr_me', 'usr_zeynep', 'usr_mehmet'] },
    ],
  },
  {
    id: 'wkt_2',
    user_id: 'usr_zeynep',
    type: 'Yoga',
    duration_minutes: 45,
    distance_km: null,
    calories: 190,
    notes: 'Güne huzurlu bir vinyasa akışı ile başladım 🧘‍♀️✨',
    image_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80',
    workout_date: new Date().toISOString().split('T')[0],
    visibility: 'friends',
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    user: SEED_PROFILES[2],
    reactions: [
      { reaction_type: '❤️', count: 5, has_user_reacted: true, user_ids: ['usr_me', 'usr_ahmet', 'usr_mehmet', 'usr_can', 'usr_zeynep'] },
      { reaction_type: '👏', count: 3, has_user_reacted: false, user_ids: ['usr_ahmet', 'usr_can', 'usr_mehmet'] },
    ],
  },
  {
    id: 'wkt_3',
    user_id: 'usr_mehmet',
    type: 'Gym',
    duration_minutes: 65,
    distance_km: null,
    calories: 520,
    notes: 'Ağır bacak antrenmanı! Squat rekoru kırıldı 💪⚡️',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    workout_date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    visibility: 'friends',
    created_at: new Date(Date.now() - 22 * 3600000).toISOString(),
    user: SEED_PROFILES[3],
    reactions: [
      { reaction_type: '💪', count: 4, has_user_reacted: true, user_ids: ['usr_me', 'usr_ahmet', 'usr_zeynep', 'usr_can'] },
      { reaction_type: '🔥', count: 3, has_user_reacted: true, user_ids: ['usr_me', 'usr_ahmet', 'usr_can'] },
    ],
  },
  {
    id: 'wkt_4',
    user_id: 'usr_me',
    type: 'Cycling',
    duration_minutes: 50,
    distance_km: 18.2,
    calories: 440,
    notes: 'Rüzgarlı havada harika tempolu bisiklet sürüşü 🚴‍♂️',
    image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266010b?w=800&auto=format&fit=crop&q=80',
    workout_date: new Date().toISOString().split('T')[0],
    visibility: 'friends',
    created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    user: SEED_PROFILES[0],
    reactions: [
      { reaction_type: '🔥', count: 3, has_user_reacted: false, user_ids: ['usr_ahmet', 'usr_zeynep', 'usr_can'] },
      { reaction_type: '👏', count: 2, has_user_reacted: false, user_ids: ['usr_mehmet', 'usr_ahmet'] },
    ],
  },
  {
    id: 'wkt_5',
    user_id: 'usr_can',
    type: 'Basketball',
    duration_minutes: 60,
    distance_km: 3.5,
    calories: 460,
    notes: '3x3 Maç sonrası galibiyet pozu 🏀⚡️',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
    workout_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    visibility: 'friends',
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
    user: SEED_PROFILES[4],
    reactions: [
      { reaction_type: '👏', count: 3, has_user_reacted: true, user_ids: ['usr_me', 'usr_ahmet', 'usr_mehmet'] },
    ],
  },
]

export const SEED_CHALLENGES: EnrichedChallenge[] = [
  {
    id: 'chg_1',
    creator_id: 'usr_ahmet',
    title: '30 Günde 20 Antrenman 🔥',
    description: 'Ay sonuna kadar disiplinini koru, 20 antrenmanı tamamla!',
    challenge_type: 'count',
    target_value: 20,
    start_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 20 * 86400000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    days_remaining: 20,
    creator: SEED_PROFILES[1],
    user_progress: 14,
    is_user_member: true,
    members: [
      { id: 'cm_1', challenge_id: 'chg_1', user_id: 'usr_ahmet', progress: 16, joined_at: new Date(Date.now() - 10 * 86400000).toISOString(), user: SEED_PROFILES[1] },
      { id: 'cm_2', challenge_id: 'chg_1', user_id: 'usr_me', progress: 14, joined_at: new Date(Date.now() - 9 * 86400000).toISOString(), user: SEED_PROFILES[0] },
      { id: 'cm_3', challenge_id: 'chg_3', user_id: 'usr_zeynep', progress: 11, joined_at: new Date(Date.now() - 8 * 86400000).toISOString(), user: SEED_PROFILES[2] },
      { id: 'cm_4', challenge_id: 'chg_4', user_id: 'usr_mehmet', progress: 9, joined_at: new Date(Date.now() - 8 * 86400000).toISOString(), user: SEED_PROFILES[3] },
    ],
  },
  {
    id: 'chg_2',
    creator_id: 'usr_me',
    title: 'Bu Hafta 50 KM Hedefi 🏃‍♂️',
    description: 'Koşu, yürüyüş ve bisiklet mesafelerini birleştir, 50 km sınırını aş.',
    challenge_type: 'distance',
    target_value: 50,
    start_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    days_remaining: 4,
    creator: SEED_PROFILES[0],
    user_progress: 32.5,
    is_user_member: true,
    members: [
      { id: 'cm_5', challenge_id: 'chg_2', user_id: 'usr_me', progress: 32.5, joined_at: new Date(Date.now() - 3 * 86400000).toISOString(), user: SEED_PROFILES[0] },
      { id: 'cm_6', challenge_id: 'chg_2', user_id: 'usr_ahmet', progress: 28.0, joined_at: new Date(Date.now() - 3 * 86400000).toISOString(), user: SEED_PROFILES[1] },
      { id: 'cm_7', challenge_id: 'chg_2', user_id: 'usr_can', progress: 21.4, joined_at: new Date(Date.now() - 2 * 86400000).toISOString(), user: SEED_PROFILES[4] },
    ],
  },
  {
    id: 'chg_3',
    creator_id: 'usr_zeynep',
    title: '10 Saat Spor Challenge ⏱️',
    description: 'Toplam 600 dakika antrenman süresine ulaş!',
    challenge_type: 'duration',
    target_value: 600,
    start_date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 9 * 86400000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    days_remaining: 9,
    creator: SEED_PROFILES[2],
    user_progress: 240,
    is_user_member: true,
    members: [
      { id: 'cm_8', challenge_id: 'chg_3', user_id: 'usr_zeynep', progress: 380, joined_at: new Date(Date.now() - 5 * 86400000).toISOString(), user: SEED_PROFILES[2] },
      { id: 'cm_9', challenge_id: 'chg_3', user_id: 'usr_mehmet', progress: 310, joined_at: new Date(Date.now() - 4 * 86400000).toISOString(), user: SEED_PROFILES[3] },
      { id: 'cm_10', challenge_id: 'chg_3', user_id: 'usr_me', progress: 240, joined_at: new Date(Date.now() - 4 * 86400000).toISOString(), user: SEED_PROFILES[0] },
    ],
  },
]

export const SEED_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    user_id: 'usr_me',
    type: 'WORKOUT_REACTION',
    title: 'Antrenmanın Alev Aldı! 🔥',
    message: 'Ahmet Kaya ve 2 kişi bisiklet antrenmanına 🔥 tepkisi verdi.',
    reference_id: 'wkt_4',
    is_read: false,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'notif_2',
    user_id: 'usr_me',
    type: 'CHALLENGE_INVITE',
    title: 'Yeni Challenge Daveti ⚔️',
    message: 'Zeynep Demir seni "10 Saat Spor Challenge" yarışına davet etti.',
    reference_id: 'chg_3',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'notif_3',
    user_id: 'usr_me',
    type: 'FRIEND_ACCEPTED',
    title: 'Arkadaşlık Kabul Edildi 👋',
    message: 'Can Arslan arkadaşlık isteğini kabul etti.',
    reference_id: 'usr_can',
    is_read: true,
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'notif_4',
    user_id: 'usr_me',
    type: 'ACHIEVEMENT_UNLOCKED',
    title: 'Rozet Kazanıldı! 🏆',
    message: '"Haftalık Seri 🔥" rozeti ve +50 XP hesabına tanımlandı.',
    reference_id: null,
    is_read: true,
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
]

export const SEED_ACHIEVEMENTS: Achievement[] = [
  { id: 'ach_1', key: 'first_workout', title: 'İlk Adım 👟', description: 'İlk antrenmanını tamamladın!', icon: '👟', xp_reward: 25 },
  { id: 'ach_2', key: 'streak_7', title: 'Haftalık Seri 🔥', description: '7 gün boyunca aralıksız antrenman yaptın!', icon: '🔥', xp_reward: 50 },
  { id: 'ach_3', key: 'workouts_10', title: 'Disiplin Abidesi 🏋️', description: '10 antrenman barajını aştın!', icon: '🏋️', xp_reward: 50 },
  { id: 'ach_4', key: 'workouts_25', title: 'Yarı Yüzlük 🎯', description: '25 antrenman tamamladın!', icon: '🎯', xp_reward: 100 },
  { id: 'ach_5', key: 'workouts_50', title: 'Efsane Sporcu 🏆', description: '50 antrenman seviyesine ulaştın!', icon: '🏆', xp_reward: 200 },
  { id: 'ach_6', key: 'first_challenge', title: 'Meydan Okuyan ⚔️', description: 'İlk challenge\'ına katıldın!', icon: '⚔️', xp_reward: 30 },
  { id: 'ach_7', key: 'challenge_winner', title: 'Şampiyon 👑', description: 'Bir challenge\'ı birincilikle bitirdin!', icon: '👑', xp_reward: 150 },
]
